package Percenatagepaytype;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class p1 
{
	public static void main(String[]args) throws InterruptedException
	{
		System.setProperty("webdriver.chrome.driver","./Drivers/chromedriver.exe");
		ChromeDriver driver=new ChromeDriver();
		Actions act = new Actions(driver);
	    driver.manage().window().maximize();
		driver.get("https://app-test.rigbot.com");
		Thread.sleep(10000);
	    driver.findElement(By.xpath("//input[@placeholder='Username']")).sendKeys("shankargowdasup");
		Thread.sleep(5000);
	    driver.findElement(By.name("password")).sendKeys("shankargowdasup01");
		Thread.sleep(5000);
		driver.findElement(By.xpath("//button[.='Log In']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//input[@data-pc-name='inputtext']")).sendKeys("prg");
		Thread.sleep(5000);
		driver.findElement(By.xpath("//span[.='PRG Express']")).click();
		Thread.sleep(5000);
	    driver.findElement(By.xpath("//a[@data-qa-menu-item='Loads']")).click();
	    Thread.sleep(3000);
	    driver.findElement(By.xpath("//span[.='Settings']")).click();
		Thread.sleep(3000);
		 act.sendKeys(Keys.PAGE_DOWN).build().perform(); 
	    driver.findElement(By.xpath("(//div[@class='settingsLayout-groupItems-item'])[13]")).click();
	    Thread.sleep(15000);
        driver.findElement(By.xpath("//input[@data-pc-section='root']")).sendKeys("Deran");
        Thread.sleep(5000);
        driver.findElement(By.xpath("(//div[@class='new-ui-driver-avatar new-ui-initials-modify'])[1]")).click();
        Thread.sleep(5000);
        driver.findElement(By.xpath("//a[.='Driver Pay ']")).click();
        Thread.sleep(5000);
        driver.findElement(By.xpath("//span[@class='accordionExapndLabel']")).click();
        Thread.sleep(5000);
        act.sendKeys(Keys.PAGE_DOWN).build().perform(); 
        Thread.sleep(3000);
        act.sendKeys(Keys.PAGE_DOWN).build().perform();   
        System.out.println("Scroll down perfomed");
        Thread.sleep(5000);
        driver.findElement(By.xpath("//input[@placeholder='Enter Percentage']")).sendKeys("33.55");
        Thread.sleep(5000);
        act.sendKeys(Keys.PAGE_UP).build().perform(); 
        Thread.sleep(3000);
        act.sendKeys(Keys.PAGE_UP).build().perform();   
        driver.findElement(By.xpath("//button[.='Update']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//span[.='Settings']")).click();
        Thread.sleep(5000);
        driver.findElement(By.xpath("//a[@data-qa-menu-item='Loads']")).click();
 	    Thread.sleep(10000);
 	    driver.findElement(By.xpath("//button[@class='btn btn-consolidation-view']")).click();
 	   	Thread.sleep(2000);
 	    driver.findElement(By.xpath("(//input[@placeholder='Enter'])[1]")).sendKeys("J6772GDNNJJEBS");
 	    Thread.sleep(5000);
 	    driver.findElement(By.xpath("(//span[@data-pc-section='input'])[1]")).click();
 	    Thread.sleep(2000);
 	    driver.findElement(By.xpath("//input[@data-pc-section='filterinput']")).sendKeys("shankar");
 	    Thread.sleep(2000);
        driver.findElement(By.xpath("//div[@class='p-dropdown-items-wrapper']")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("(//input[@class='form-control'])[1]")).click();
 	    Thread.sleep(2000);
 	    driver.findElement(By.xpath("(//td[@data-value='12'])[1]")).click();
 	    Thread.sleep(2000);
	    driver.findElement(By.xpath("(//input[@id='shipperConsigneeName'])[1]")).click();
	   	WebElement key1=driver.findElement(By.xpath("(//input[@id='shipperConsigneeName'])[1]"));
	    Thread.sleep(5000);
	    key1.sendKeys("WQ Shipper");
	 	key1.sendKeys(Keys.ENTER);
	 	driver.findElement(By.xpath("(//input[@class='form-control'])[2]")).click();
 	    Thread.sleep(2000);
 	    driver.findElement(By.xpath("(//td[@data-value='16'])[2]")).click();
 	    Thread.sleep(2000);
	    driver.findElement(By.xpath("(//input[@id='shipperConsigneeName'])[2]")).click();
	    WebElement key2=driver.findElement(By.xpath("(//input[@id='shipperConsigneeName'])[2]"));
	    key2.sendKeys("sgg");
	    Thread.sleep(2000);
	    key2.sendKeys(Keys.ENTER);
	    Thread.sleep(2000);
	    act.sendKeys(Keys.PAGE_DOWN).build().perform(); 
	    Thread.sleep(2000);
        driver.findElement(By.xpath("//input[@role='spinbutton']")).sendKeys("41.2");
        Thread.sleep(2000);
        driver.findElement(By.xpath("(//div[@class='p-multiselect-label p-placeholder'])[1]")).click();
        Thread.sleep(5000);
        driver.findElement(By.xpath("(//input[@data-pc-section='root'])[6]")).sendKeys("Deran");
        Thread.sleep(5000);
        driver.findElement(By.xpath("//div[@class='p-checkbox-box']")).click();
        Thread.sleep(5000);
 	    driver.findElement(By.xpath("(//span[.='Select Truck'])[1]")).click();
 	    Thread.sleep(2000);
 	 	driver.findElement(By.xpath("(//input[@autocomplete='off'])[3]")).sendKeys("Belown");
 	 	Thread.sleep(5000);
 	 	driver.findElement(By.xpath("//div[@class='p-dropdown-items-wrapper']")).click();
 	    Thread.sleep(5000);
        driver.findElement(By.xpath("(//div[@class='step '])[3]")).click();
 	    Thread.sleep(2000);
 	    driver.findElement(By.xpath("(//button[@data-pc-section='root'])[2]")).click();
 	    Thread.sleep(15000);
 	  	driver.findElement(By.xpath("//p[.='Driver Pay']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//input[@placeholder='Search Driver pay']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//input[@placeholder='Search Driver pay']")).sendKeys("Deran");
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//div[@style='text-align: center;']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//div[@data-pc-section='checkbox']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//button[.=' + Create Pay']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//span[.='+ Add Expense']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//input[@placeholder='Search...']")).sendKeys("demons");
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("(//input[@type='checkbox'])[1]")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//button[.=' + Add ']")).click();
 	  	Thread.sleep(5000);
 	  	JavascriptExecutor js = (JavascriptExecutor) driver;
 	  	js.executeScript("window.scrollBy(0,-1000)");
 	  	driver.findElement(By.xpath("//button[@class='btn dropdown-toggle btn btn-primary']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//a[.='Proceed to pay']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("(//div[@data-pc-name='dropdown'])[1]")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//li[.='2312']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("(//div[@aria-label='Select'])[2]")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//li[.='ACH Payment']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//button[.='Send Payment']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//input[@placeholder='Enter Routing Number']")).sendKeys("011401533");
 	  	Thread.sleep(2000);
 	  	driver.findElement(By.xpath("//input[@placeholder='Enter Account Number']")).sendKeys("00212369");
 	  	Thread.sleep(2000);
 	  	driver.findElement(By.xpath("//input[@placeholder='Confirm Account Number']")).sendKeys("00212369");
 	  	Thread.sleep(2000);
 	  	driver.findElement(By.xpath("//button[.='Confirm & Send Payment']")).click();
 	  	Thread.sleep(5000);
 	  	driver.findElement(By.xpath("//a[.='Driver pay']")).click();
 	  	Thread.sleep(5000);
        driver.quit();		
		
	}



	}


